"""
Django settings for moonShot project.

Generated by 'django-admin startproject' using Django 1.9.2.

For more information on this file, see
https://docs.djangoproject.com/en/1.9/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.9/ref/settings/
"""

import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

PROJECT_DIR = os.path.abspath(os.path.join(BASE_DIR, '..'))
# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.9/howto/deployment/checklist/
######## Create Log Dir ##############
LOGS_DIR = os.path.join(BASE_DIR, 'logs')
if not os.path.isdir(LOGS_DIR):
    os.makedirs(LOGS_DIR)
##################################
# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'k6-fstzw1)7&jlu19iv@c^w09iy&u8+ikv2c&mf^4e!^vchzo!'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition
MY_APPS = [    
    'moonShot',
    'moonShot_structure',
    'moonShot_api',
    ]
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'djcelery',
    'kombu.transport.django',
]
INSTALLED_APPS.extend(MY_APPS)



MIDDLEWARE_CLASSES = [
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.auth.middleware.SessionAuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware'
]

ROOT_URLCONF = 'moonShot.urls'



WSGI_APPLICATION = 'moonShot.wsgi.application'


# Database
# https://docs.djangoproject.com/en/1.9/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql_psycopg2',
        'NAME': "moonshot",
        'USER': "postgres",
        'PASSWORD': "postgres",
        'HOST': "localhost",
        'PORT': 5432,
    }
}

#Celery
BROKER_URL = 'django://'
CELERY_RESULT_BACKEND = 'djcelery.backends.database:DatabaseBackend'
#

# Password validation
# https://docs.djangoproject.com/en/1.9/ref/settings/#auth-password-validators



# Internationalization
# https://docs.djangoproject.com/en/1.9/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.9/howto/static-files/

STATIC_URL = '/static/' 
STATICFILES_DIRS = []
TEMPLATE_DIRS = []
for app in MY_APPS:
    STATICFILES_DIRS.append(os.path.join(PROJECT_DIR, app, 'static'))
    TEMPLATE_DIRS.append(os.path.join(PROJECT_DIR, app, 'templates'))
MAX_CHAR_SIZE = 256





LOGGING = {
    'version': 1,
    'disable_existing_loggers': True,
    'formatters': {
        'standard': {
            'format' : "[%(asctime)s] %(levelname)s [%(name)s:%(lineno)s] %(message)s",
            'datefmt' : "%d/%b/%Y %H:%M:%S"
        },
    },
    'handlers': {
        'logfile': {
            'level':'DEBUG',
            'class':'logging.handlers.RotatingFileHandler',
            'filename': LOGS_DIR + "/moonshot.log",
            'maxBytes': 2 * 1024 * 1024, # 2 mega.
            'backupCount': 10,
            'formatter': 'standard',
        },
        'console':{
            'level':'INFO',
            'class':'logging.StreamHandler',
            'formatter': 'standard'
        }
    },
    'loggers': {
        'moonShot': {
            'handlers': ['console', 'logfile'],
            'level': 'DEBUG',
        },
    }
}